- name: setup cart server
  hosts: cart
  become: yes

  tasks:
    - name: install curl
      ansible.builtin.command: yum install -y curl
      changed_when: false

    - name: download NodeJS 16 tarball
      ansible.builtin.get_url:
        url: https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz
        dest: /opt/node-v16.20.2-linux-x64.tar.xz

    - name: extract NodeJS 16
      ansible.builtin.unarchive:
        src: /opt/node-v16.20.2-linux-x64.tar.xz
        dest: /opt
        remote_src: yes

    - name: create node and npm symlinks
      ansible.builtin.file:
        src: /opt/node-v16.20.2-linux-x64/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        state: link
      loop:
        - node
        - npm

    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        comment: RoboShop System user
        system: true
        shell: /sbin/nologin
        home: /app

    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        state: directory
        path: /app
        owner: roboshop
        group: roboshop

    - name: delete existing cart zip
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent

    - name: download cart application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: extract cart application
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: install node dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: daemon reload, enable and start cart service
      ansible.builtin.systemd:
        name: cart
        enabled: true
        state: started
        daemon_reload: true
