- name: setup catalogue server
  hosts: catalogue
  become: yes
  tasks:
    - name: install curl
      ansible.builtin.command: yum install -y curl
      changed_when: false

    - name: download NodeJS 16 tarball
      ansible.builtin.get_url:
        url: https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz
        dest: /opt/node-v16.20.2-linux-x64.tar.xz

    - name: extract NodeJS
      ansible.builtin.unarchive:
        src: /opt/node-v16.20.2-linux-x64.tar.xz
        dest: /opt
        remote_src: yes

    - name: create node symlinks
      ansible.builtin.file:
        src: /opt/node-v16.20.2-linux-x64/bin/{{ item }}
        dest: /usr/local/bin/{{ item }}
        state: link
      loop:
        - node
        - npm

    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        comment: RoboShop System user
        system: true
        shell: /sbin/nologin
        home: /app

    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        state: directory
        path: /app
        owner: roboshop
        group: roboshop

    - name: delete catalogue zip
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent

    - name: download catalogue application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: extract catalogue application
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: install node dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: daemon reload and start catalogue
      ansible.builtin.systemd:
        name: catalogue
        enabled: true
        state: started
        daemon_reload: true
