- name: setup redis server
  hosts: redis
  become: yes
  tasks:
    - name: install redis
      ansible.builtin.command: yum install -y redis
      register: redisinstall
      changed_when: "'Complete!' in redisinstall.stdout"

    - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'

    - name: disable protected mode
      ansible.builtin.lineinfile:
        path: /etc/redis.conf
        regexp: '^protected-mode'
        line: 'protected-mode no'

    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        enabled: yes
        state: started
