- name: configure shipping server
  hosts: shipping
  become: yes
  tasks:
    - name: install maven and mysql client
      ansible.builtin.command: yum install -y maven mysql
      register: maven
      changed_when: "'Complete!' in maven.stdout"

    - name: install mysql python libraries
      ansible.builtin.pip:
        executable: pip3
        name:
          - cryptography
          - PyMySQL

    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        system: true
        shell: /sbin/nologin
        home: /app

    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        state: directory
        path: /app
        owner: roboshop
        group: roboshop

    - name: delete shipping file
      ansible.builtin.file:
        path: /tmp/shipping.zip
        state: absent

    - name: download shipping application
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: extract shipping application
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: build jar with maven
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: move jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: import shipping schema (without FULLTEXT indexes)
      ansible.builtin.shell: sed 's/FULLTEXT/ /gI' /app/db/schema.sql | mysql -h 34.207.183.226 -uroot -p'RoboShop@1'
      args:
        chdir: /app/db

    - name: import master data (without FULLTEXT indexes)
      ansible.builtin.shell: sed 's/FULLTEXT/ /gI' /app/db/master-data.sql | mysql -h 34.207.183.226 -uroot -p'RoboShop@1'
      args:
        chdir: /app/db

    - name: copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon reload enable and start shipping
      ansible.builtin.systemd:
        name: shipping
        enabled: true
        state: started
        daemon_reload: true
